//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectiveShoppingMvc.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string Date { get; set; }
        public double Price { get; set; }
        public double UnitQuantity { get; set; }
        public bool IsEnabled { get; set; }
        public int ShopId { get; set; }
        public int CategoryId { get; set; }

        [JsonIgnore]
        public virtual Shop Shop { get; set; }
        public virtual Category Category { get; set; }
    }
}
